[Definition]
# 启动时创建表和集合
actionstart = nft add table inet f2b-table; \
              nft add set inet f2b-table addr-set-<name> { type ipv4_addr; flags interval; }

# 停止时删除表
actionstop  = nft delete table inet f2b-table

# 检查表是否存在
actioncheck = nft list table inet f2b-table

# 封禁：把 IP 加入集合
actionban   = nft add element inet f2b-table addr-set-<name> { <ip> }

# 解封：把 IP 从集合里移除
actionunban = nft delete element inet f2b-table addr-set-<name> { <ip> }
