[Definition]
# 不再创建表和集合，交给 nftables 配置文件持久化
actionstart =
actionstop  =
actioncheck = nft list set inet f2b-table addr-set-sshd
actionban   = nft add element inet f2b-table addr-set-sshd { <ip> }
actionunban = nft delete element inet f2b-table addr-set-sshd { <ip> }
